### ISSUE TITLE
Support for Spring WebFlux [DATAREST-933]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-rest#1299]
**[Abhijit Sarkar](https://jira.spring.io/secure/ViewProfile.jspa?name=asarkar)** opened **[DATAREST-933](https://jira.spring.io/browse/DATAREST-933?redirect=false)** and commented

Support Spring Data REST in Boot using Spring Web Reactive.

Original ticket:
https://jira.spring.io/browse/SPR-14878?focusedCommentId=133196&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-133196

---

**Affects:** 2.4.6 (Gosling SR6)

14 votes, 23 watchers

**Comment by alsaghir** [comment]
Is there any update on this ?. I'm facing the decision to move to the reactive stack but spring data rest really does great work of productivity so I'd like not to start using webflux while it's still not supported.

**Comment by mp911de** [comment]
The points of https://github.com/spring-projects/spring-data-rest/issues/1299#issuecomment-752913911 are still valid. The entire team would be basically busy with rewriting Spring Data REST for one to two years. So from that point of view, we do not plan to go after this change.

**Comment by odrotbohm** [comment]
What Mark said. I'd still be interested to hear what the use case of Spring Data REST is in a reactive scenario. The functionality Spring Data REST provides doesn't necessarily play into the strengths of a reactive programming model (streaming, large data sets, backpressure) etc. It's much more focussing on stateful resources and making it easy to implement state transitions on them.

Would love to learn about your particular motivation. 🙃
