### ISSUE TITLE
Switch to disable PUT for creation on item resources by default [DATAREST-948]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-rest#1318]
**[Abhijit Sarkar](https://jira.spring.io/secure/ViewProfile.jspa?name=asarkar)** opened **[DATAREST-948](https://jira.spring.io/browse/DATAREST-948?redirect=false)** and commented

`PUT /\{resource}/\{id`} ends up creating a new resource if it doesn't exist. According to the [doc](http://docs.spring.io/spring-data/rest/docs/current/reference/html/#repository-resources.item-resource) for the item resource, the behavior should be as follows:

> Replaces the state of the target resource with the supplied request body.

Thus for a non-existent `id`, I'd expect a HTTP status 404, not a new resource (you can't "replace" something that doesn't exist). I do not expect the user to call my API with a given id to use for a new resource, because the id almost always is internal implementation specific (like an auto-increment key in the DB). Note that `POST /\{resource\`} behavior is to create a new item resource and add it to the collection.

---

**Affects:** 2.5.5 (Hopper SR5)

**Issue Links:**
- [DATAREST-180](https://jira.spring.io/browse/DATAREST-180) Update (Http PUT) operation should not create new entity

- [DATAREST-1034](https://jira.spring.io/browse/DATAREST-1034) Allow overriding exposure defined at the type level on the method

**Referenced from:** commits https://github.com/spring-projects/spring-data-rest/commit/ca668eb08e123ec6b41e3749ef9dc6f75009e2a5, https://github.com/spring-projects/spring-data-rest/commit/c5c7fa9d1957f4e7796078f78a444db3bd907d26, https://github.com/spring-projects/spring-data-rest/commit/c3101b3c8382adc16834a88376f8efe7570d956e, https://github.com/spring-projects/spring-data-rest/commit/28383ba81318922d6b996741f12509d2de631512, https://github.com/spring-projects/spring-data-rest/commit/a1454058d9956194a9ae376411c69c263405bc8d, https://github.com/spring-projects/spring-data-rest/commit/1762b45e7b4797a8add30df0d6324de7524ff714, https://github.com/spring-projects/spring-data-rest/commit/c5a3262c66725dc652a4b7441d403a72889c3cb9, https://github.com/spring-projects/spring-data-rest/commit/c355c75a07a7f7f669d31ad8cd7eff222b50569a

3 votes, 9 watchers

**Comment by davidmpaz** [comment]
And some years later I am asking myself if this switch was implemented. I am also interested in being able to configure whether PUT creates resources if it does not exist, or throw a 404.
