### ISSUE TITLE
How to fix  HTTP parameter/path pollution attack Spring Rest [DATAREST-1116]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-rest#1477]
**[vaquar khan](https://jira.spring.io/secure/ViewProfile.jspa?name=vaquarjsr368@gmail.com)** opened **[DATAREST-1116](https://jira.spring.io/browse/DATAREST-1116?redirect=false)** and commented

Extracting parameters from HTTP message and getting resource URLs could be vulnerable to injection attacks that may change the semantics of the intended resource. Two classes of attacks are relevant here: HTTP parameter/path pollution (HPPP) and Server-Side Request Forgery (SSRF). Remember that our attacker has full control over the HTTP request or the HTTP response.

In an HPPP (HTTP parameter/path pollution attack), a parameter is used to compose the resource URL to be used to prepare a REST request for a resource (or generate an embedded link). The problem is that the attacker may either alter the path or add/overwrite unexpected parameters in the “query string”. Additionally, REST frameworks may use a parameter (like _method) to allow the specification of a REST verb different from the incoming HTTP method, so a GET request could be interpreted as a PUT operation. An attacker may change the semantics of the REST resource URL.

find more info https://www.cs.columbia.edu/~vpk/papers/arc.acns12.pdf

Example :

For example: if testing the search_string parameter in the query string, the request URL would include that parameter name and value.

http://example.com/?search_string=kittens
The particular parameter might be hidden among several other parameters, but the approach is the same; leave the other parameters in place and append the duplicate.

http://example.com/?mode=guest&search_string=kittens&num_results=100
Append the same parameter with a different value

http://example.com/?mode=guest&search_string=kittens&num_results=100&search_string=puppies
and submit the new request.

Question:

Spring Rest ,Spring MVC and Spring Security doesn't provide any in built support to fix HPPP issue.How can we fix inside of Spring frameworks ?

https://stackoverflow.com/questions/45250843/how-to-fix-http-parameter-path-pollution-attack-spring-rest

---
No further details from [DATAREST-1116](https://jira.spring.io/browse/DATAREST-1116?redirect=false)

**Comment by vishnoor** [comment]
Copied the OP's own solution from STackOverflow https://stackoverflow.com/questions/45250843/how-to-fix-http-parameter-path-pollution-attack-spring-rest
