### ISSUE TITLE
Deserialize snake case JSON does not work for association fields [DATAREST-1232]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-rest#1591]
**[Julien Roy](https://jira.spring.io/secure/ViewProfile.jspa?name=vanroy)** opened **[DATAREST-1232](https://jira.spring.io/browse/DATAREST-1232?redirect=false)** and commented

When POST / PUT / PATCH entity that contains association field in snake case Json format, the association field is not mapped.

I think is due to an issue in PersistentEntityJackson2Module#AssociationUriResolvingDeserializerModifier class.

JSON body sample :

{ "first_name" : "Bilbo", "grand_father" : "/persons/1"}

Entity sample :

`@Entity`
public class Person {
`@Id` `@GeneratedValue` private Long id;
private String firstName;
`@ManyToOne`  private Person grandFather;
}

Pull request proposed here : https://github.com/spring-projects/spring-data-rest/pull/291

---

**Affects:** 3.0.6 (Kay SR6)

**Comment by odrotbohm** [comment]
This ticket came up in the context of #2165, and we think the original problem should be solved with the fix for that. Please give the snapshots a try if you manage to find the time.
