### ISSUE TITLE
Add HAL Explorer module as alternative to HAL Browser [DATAREST-1386]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-rest#1746]
**[Oliver Drotbohm](https://jira.spring.io/secure/ViewProfile.jspa?name=olivergierke)** opened **[DATAREST-1386](https://jira.spring.io/browse/DATAREST-1386?redirect=false)** and commented

HAL Browser does not seem to be actively maintained anymore and the WebJar ships with a jQuery version that contains a CVE. There's an alternative UI called [HAL Explorer](https://github.com/toedter/hal-explorer) that's more actively maintained

---
No further details from [DATAREST-1386](https://jira.spring.io/browse/DATAREST-1386?redirect=false)

**Comment by lu-cheng** [comment]
I personally think that the ease of use of this tool is more important than proactive updates. A year has passed. I checked the PR of hal-explorer and did actively update the dependent version, but the ease of use did not improve. Just a suggestion, is it possible to provide additional hal-browser integration?

**Comment by odrotbohm** [comment]
Everything but seamless integration of third-party tooling is out of scope for Spring Data REST. HAL Explorer is open source, too. So if you have suggestions on how to improve things over there or even want to actively contribute I suggest
