### ISSUE TITLE
2.4.0/2.4.1 sprint-boot Rest Repositories initializr project reports lots of Beans is not eligible for getting processed by all BeanPostProcessors [DATAREST-1590]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-rest#1921]
**[Yohann Dumais](https://jira.spring.io/secure/ViewProfile.jspa?name=JIRAUSER50787)** opened **[DATAREST-1590](https://jira.spring.io/browse/DATAREST-1590?redirect=false)** and commented

I just started using Spring Boot and noticed a lot of INFO messages reporting Bean 'X' of type [Y] is not eligible for getting processed by all BeanPostProcessors.

I noticed this behavior when I updated from 2.3.5.RELEASE to 2.4.0.

This repo illustrate the behavior observed : https://github.com/yohanndumais/demo-data-rest

created from spring initializr : [https://start.spring.io/...](https://start.spring.io/#!type=maven-project&language=java&platformVersion=2.4.0.RELEASE&packaging=jar&jvmVersion=11&groupId=com.example&artifactId=demo&name=demo&description=Demo%20project%20for%20Spring%20Boot&packageName=com.example.demo&dependencies=data-rest) with only Rest Repositories as a dependencies. 

I created this issue against spring-boot 2.4.0 and is still observable with 2.4.1. 

As I am new to Data Rest and spring-boot, I am concerned that I might encounter spring configuration issues. 

---

**Affects:** 3.4.2 (2020.0.2)

**Reference URL:** https://github.com/spring-projects/spring-boot/issues/24322

**Backported to:** [3.4.3 (2020.0.3)](https://github.com/spring-projects/spring-data-rest/milestone/181?closed=1)

**Comment by odrotbohm** [comment]
I forgot pushing the back-port into the 3.4.x branch. Due to that, the fix has not made it into the recent 3.4.3 release but will instead be shipped with 3.4.4 (due Feb 10th).
