### ISSUE TITLE
Using @JsonValue in embedded collection values causes an exception [DATAREST-1564]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-data-rest#1926]
**[alienisty](https://jira.spring.io/secure/ViewProfile.jspa?name=alienisty)** opened **[DATAREST-1564](https://jira.spring.io/browse/DATAREST-1564?redirect=false)** and commented

Following the update of spring-hateoas 1.1.2, the resolution of https://github.com/spring-projects/spring-hateoas/issues/1354 seems to have caused the regression.

Following a discussion with [Oliver Drotbohm](https://jira.spring.io/secure/ViewProfile.jspa?name=olivergierke) on the ticket https://github.com/spring-projects/spring-hateoas/issues/1371, he thinks the problem should be fixed in spring data rest.

Attached is a minimal reproduction project for an end to end demonstration using spring-data-rest.

A quicker demonstration of the core problem can be done with the following code.

```java
void serialisation() throws Exception {
  var value = new Value("test");
  var model = EntityModel.of(value);
  var string = objectMapper.writeValueAsString(model);
  System.out.println(string);
}
static class Value {
  @JsonValue
  String theValue;
    Value(String value) {
    this.theValue = value;
  }
}
```

Which causes the following exception when run with spring-hateoas 1.1.2:

```java
com.fasterxml.jackson.core.JsonGenerationException: Can not write a string, expecting field name (context: Object)
	at com.fasterxml.jackson.core.JsonGenerator._reportError(JsonGenerator.java:2151)
	at com.fasterxml.jackson.core.json.JsonGeneratorImpl._reportCantWriteValueExpectName(JsonGeneratorImpl.java:233)
	at com.fasterxml.jackson.core.json.JsonGeneratorImpl._verifyPrettyValueWrite(JsonGeneratorImpl.java:223)
	at com.fasterxml.jackson.core.json.WriterBasedJsonGenerator._verifyValueWrite(WriterBasedJsonGenerator.java:917)
	at com.fasterxml.jackson.core.json.WriterBasedJsonGenerator.writeString(WriterBasedJsonGenerator.java:400)
	at com.fasterxml.jackson.databind.ser.std.StringSerializer.serialize(StringSerializer.java:41)
	at com.fasterxml.jackson.databind.ser.std.JsonValueSerializer.serialize(JsonValueSerializer.java:181)
	at org.springframework.hateoas.EntityModel$MapSuppressingUnwrappingSerializer.serialize(EntityModel.java:218)
	at com.fasterxml.jackson.databind.ser.impl.UnwrappingBeanPropertyWriter.serializeAsField(UnwrappingBeanPropertyWriter.java:127)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:755)
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:178)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:480)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:319)
	at com.fasterxml.jackson.databind.ObjectMapper._writeValueAndClose(ObjectMapper.java:4407)
	at com.fasterxml.jackson.databind.ObjectMapper.writeValueAsString(ObjectMapper.java:3661)
...
```

---

**Attachments:**
- [demo.zip](https://jira.spring.io/secure/attachment/28293/demo.zip) (_71.22 kB_)

1 votes, 2 watchers

**Comment by odrotbohm** [comment]
Regarding that description there: it doesn't make sense to wrap something that is a JSON value into an `EntityModel` directly.   It works by decorating an entity into a JSON Object, i.e. we will end up with a structure like this by definition:

```json
{
  "_links" : { … },
  "someKey" : "someValue"
}
```

Except the reserved keys (`_links` in this case) are populated by the entity's fields. If the entity is supposed to be rendered as a value, there is no key to use.

That said, in the context of Spring Data REST in your example the wrapping into an `EntityModel` is a bug. We need to check whether the target element serializer is a `JsonValueSerializer` and skip the wrapping. I'll fix this here in Spring Data REST and let `EntityModel` fail the rendering with a better error message that hints at the problem.

**Comment by odrotbohm** [comment]
That's in place. Feel free to give the snapshots a try.

**Comment by dcominottim** [comment]
Thanks for the quick updates, @odrotbohm! Will test with Spring Boot 2.4.1. Can you please confirm which >= snapshot version and dependencies I need to override in order to test this?

**Comment by odrotbohm** [comment]
If you set `spring-data-bom.version` to `2020.0.3` you should see this work with Spring Data REST. For the explicit rejection of the erroneous combination of `EntityModel` and `@JsonValue` types, you also need to set `spring-hateoas.version` to `1.2.4-SNAPSHOT` although that's only needed if you want to explicitly see the exception in case you manually combine the two.

**Comment by dcominottim** [comment]
> Thanks for the quick updates, @odrotbohm! Will test with Spring Boot 2.4.1. Can you please confirm which >= snapshot version and dependencies I need to override in order to test this?

What's the best way to do that nowadays?

Tried 2 approaches (using Gradle),

1)

extra["springDataVersion"] = "2020.0.3"

`dependencyManagement {
    imports {
        mavenBom("org.springframework.data:spring-data-bom:${property("springDataVersion")}")
    }
}`

Did not work.

2) Only

`extra["spring-data-bom.version"] = "2020.0.3"`

Did not work.

I am using a standard output from the latest Spring Initializr.

If I manually specify the `spring-data-rest-mvc` dependency as in

`implementation("org.springframework.data:spring-data-rest-webmvc:3.5.0-20210118.153014-557")`

It does work fine.

**Comment by dcominottim** [comment]
> If you set `spring-data-bom.version` to `2020.0.3` you should see this work with Spring Data REST. For the explicit rejection of the erroneous combination of `EntityModel` and `@JsonValue` types, you also need to set `spring-hateoas.version` to `1.2.4-SNAPSHOT` although that's only needed if you want to explicitly see the exception in case you manually combine the two.

What's the best way to do that nowadays?

Tried 2 approaches (using Gradle),

One, manually adding the BOM:

```
extra["springDataVersion"] = "2020.0.3"

dependencyManagement {
    imports {
        mavenBom("org.springframework.data:spring-data-bom:${property("springDataVersion")}")
    }
}
```

Did not work.

Two: only setting the property:

`extra["spring-data-bom.version"] = "2020.0.3"`

Also did not work.

I am using a standard output from the latest Spring Initializr. If I manually specify the spring-data-rest-mvc dependency as in

`implementation("org.springframework.data:spring-data-rest-webmvc:3.5.0-20210118.153014-557")`

It does work fine.

**Comment by odrotbohm** [comment]
Sorry, I mistyped. You need to use `2020.0.4-SNAPSHOT` for the Spring Data dependency. Fix will be included in the next release.

**Comment by dcominottim** [comment]
Thanks a lot! That seems to have done the trick. =)
