### ISSUE TITLE
Duplicate calls of a custom HandlerInterceptor's methods after updating spring to 5.3.1

### ISSUE THREAD

**Issue by lwitzani** [spring-projects/spring-data-rest#1955]
Hi,
**Background:**
We have a Spring Boot project and recently updated our dependencies from Spring Boot 2.3.7.RELEASE to 2.4.0!
Spring Framework therefore changed from 5.2.12.RELEASE to 5.3.1

**Use case:**
We have a custom interceptor (let's call it ActivityLoggerInterceptor) that implements org.springframework.web.servlet.HandlerInterceptor
We are registering the interceptor similar to the following:
```
@Configuration
public class WebMvcConfig {

    @Bean
    public MappedInterceptor mappedInterceptor() {
        return new MappedInterceptor(
                new String[]{"/api/**"},
                new ActivityLoggerInterceptor()
        );
    }
}
```
This worked perfectly on Spring Boot 2.3.7.RELEASE / Spring 5.2.12.RELEASE meaning the handler methods preHandle and afterCompletion were called once per request.

**The issue:**
After updating to Spring Boot 2.4.0 / Spring 5.3.1 the methods preHandle and afterCompletion in our interceptor are each called twice

**Observations:**
After some debugging i found that our Interceptor is somehow now found twice (see the picture below).
![duplicateInterceptorCalls](https://user-images.githubusercontent.com/26573718/104334149-4fa58b00-54f2-11eb-9ab0-0288ba6eb239.png)

From there it goes deep into Spring ...
Because of this and because i did not find anything that our registration of the Interceptor could be wrong now, i am writing this issue. 
Looking through the closed and open issues i did not find anything that would match this problem. But it seems that something around MappedInterceptors has changed in Spring. 

Can you help me somehow :)? Thanks so much!

Best regards,
Lukas

**Comment by odrotbohm** [comment]
This in place. Feel free to give the snapshots a try.

**Comment by lwitzani** [comment]
I just tried it with 3.4.4-SNAPSHOT of branch "3.4.x" and 3.5.0-SNAPSHOT of branch "master" and can confirm that it works in both cases. 

Thanks for fixing this so quickly. Issue should be resolved with the 3.4.4 release! Nice job!

**Comment by orubel** [comment]
I believe (from just now reading the fix) that this is also effecting SimpleUrlHandlerMapping; Noticed this hasn't been added to SimpleUrlHandlerMapping and I am seeing this error:

	SimpleUrlHandlerMapping mapping = new SimpleUrlHandlerMapping();
	mapping.registerHandlers(urlMap)
	mapping.setUrlMap(urlMap);
	mapping.setOrder(1);
	mapping.setInterceptors(new Object[]{ new ApiInterceptor() })
	mapping.setApplicationContext(context);
	mapping.initApplicationContext()

**Comment by odrotbohm** [comment]
`SimpleUrlHandlerMapping` is part of Spring MVC. If you think, you have identified an issue with it, please file a ticket in the [Spring MVC tracker](https://github.com/spring-projects/spring-framework).

**Comment by orubel** [comment]
will do. Thx.
