### ISSUE TITLE
ALPS metadata customization via rest-messages.properties is not working for 2-level nested POJOs

### ISSUE THREAD

**Issue by dcominottim** [spring-projects/spring-data-rest#1956]
Considering an hierarchy

```
@Entity
@Table(name = PointOfInterest.Table.NAME)
@Access(AccessType.FIELD)
class PointOfInterest(
    id: UUID = UUID.randomUUID(),
    name: PointOfInterestName,
    location: Location
) {
    @field:Id
    var id: UUID = id
        protected set

    @Embedded
    @AttributeOverride(
        name = PointOfInterestName.Attributes.VALUE,
        column = Column(name = "name", unique = true)
    )
    @Valid
    var name: PointOfInterestName = name
        protected set

    @Embedded
    @Valid
    var location: Location = location
        protected set

    object Table {
        const val NAME = "point_of_interest"
    }

    object Rest {
        const val COLLECTION = "pointsOfInterest"
    }
}
```

```
@Embeddable
data class Location(
    @field:Embedded
    @field:AttributeOverride(
        name = GeoPoint.Attributes.VALUE,
        column = Column(name = Attributes.X)
    )
    @field:Valid
    val x: GeoPoint,

    @field:Embedded
    @field:AttributeOverride(
        name = GeoPoint.Attributes.VALUE,
        column = Column(name = Attributes.Y)
    )
    @field:Valid
    val y: GeoPoint
) {

    object Attributes {
        const val X = "x"
        const val Y = "y"
    }
}
```

```
@Embeddable
data class GeoPoint
    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    constructor(@field:PositiveOrZero @field:JsonValue val value: Int) {

    object Attributes {
        const val VALUE = "value"
    }
}
```

and a rest-messages.properties file

```
rest.description.pointOfInterest=A collection of Points of Interest (POIs)
rest.description.pointOfInterest.location=A POI's location in terms of non-negative integer coordinates X and Y
rest.description.pointOfInterest.location.x=A non-negative integer coordinate that represents the position in the X axis
rest.description.pointOfInterest.location.y=A non-negative integer coordinate that represents the position in the Y axis
```

the generated ALPS at the `profile` URL is

```
{
  "alps": {
    "version": "1.0",
    "descriptor": [
      {
        "id": "pointOfInterest-representation",
        "href": "http://localhost:8080/profile/pointsOfInterest",
        "doc": {
          "format": "TEXT",
          "value": "A collection of Points of Interests (POIs)"
        },
        "descriptor": [
          {
            "name": "name",
            "type": "SEMANTIC"
          },
          {
            "name": "location",
            "type": "SEMANTIC",
            "doc": {
              "format": "TEXT",
              "value": "A POI's location in terms of non-negative integer coordinates X and Y"
            }
          }
        ]
      },
      ...
    ]
  }
}
```
so that the `rest.description.pointOfInterest.location.x` and `rest.description.pointOfInterest.location.y` properties are ignored.

**Comment by gregturn** [comment]
Doesn't JPA's embedded annotations result in the two types being mapped into a single table?

In essence, doesn't this map `X` and `Y` into the `pointOfInterest` table (`POINT_OF_INTEREST.X` and `POINT_OF_INTEREST.Y`) instead of `POINT_OF_INTEREST.LOCATION.X` / `POINT_OF_INTEREST.LOCATION.Y`?

**Comment by gregturn** [comment]
Per the ALPS spec, nested fields aren't supported.

This may confusing, given the spec itself mentions "nested descriptors". That's because they use the "descriptor" multiple times with in a structure. 

But if you look at https://tools.ietf.org/html/draft-amundsen-richardson-foster-alps-04, you'll find all the examples end when it gets to the named attributes at one level. That is most certainly driven by the fact that these profile types are aimed at autogenerating HTML forms, which are historically flat.

In essence, if you are wanting to generate hypermedia that can drives a form, you're better off having a simple, flat DTO that facilitates this. Then you handle mapping things either at the controller level, or possibly deferring to the service level if the rules for translation are complex and would result in a thick controller.

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
