### ISSUE TITLE
@RestResource(exported = false) is not Polymorphic

### ISSUE THREAD

**Issue by ashishna** [spring-projects/spring-data-rest#1963]
I want to disable all `DELETE` operation using using generics and super interfaces. Any repository which extends from `BaseResourceRepository` should not export `DELETE` verb. I am using groovy

```
@NoRepositoryBean
interface BaseResourceRepository<T extends BaseEntity, ID extends Serializable> extends PagingAndSortingRepository<T, ID> {
    @Override
    @RestResource(exported = false)
    void delete(T t)
}

@RepositoryRestResource(collectionResourceRel = "contacts", path = "contacts")
interface ContactRepository extends BaseResourceRepository<Contact, Long> {

}
```
I want to disable the `DELETE` operation for `/contacts` endpoint

This configuration is still allowing me to DELETE the contact resource

**Comment by sullrich84** [comment]
I am doing the same thing with one difference, instead of setting `@RestResource(exported = false)` I'm disabling _DELETE_ requests via `@PreAuthorize`:

```
@NoRepositoryBean
public interface BaseRepository<E, ID> extends PagingAndSortingRepository<E, ID>
{
    @Override
    @PreAuthorize("hasRole('ROLE_ADMINISTRATOR')")
    void deleteById (ID id);

    @Override
    @PreAuthorize("hasRole('ROLE_ADMINISTRATOR')")
    void delete (E entity);

    @Override
    @PreAuthorize("hasRole('ROLE_ADMINISTRATOR')")
    void deleteAll (Iterable<? extends E> entities);

    @Override
    @PreAuthorize("hasRole('ROLE_ADMINISTRATOR')")
    void deleteAll ();
}
```

**Comment by ashishna** [comment]
> I am doing the same thing with one difference, instead of setting `@RestResource(exported = false)` I'm restricting _DELETE_ requests via `@PreAuthorize`:
> 
> ```
> @NoRepositoryBean
> public interface BaseRepository<E, ID> extends PagingAndSortingRepository<E, ID>
> {
>     @Override
>     @PreAuthorize("denyAll()")
>     void deleteById (ID id);
> 
>     @Override
>     @PreAuthorize("denyAll()")
>     void delete (E entity);
> 
>     @Override
>     @PreAuthorize("denyAll()")
>     void deleteAll (Iterable<? extends E> entities);
> 
>     @Override
>     @PreAuthorize("denyAll()")
>     void deleteAll ();
> }
> ```

Thanks for the reply, I am not using spring security to guard methods, hence cant use this.

**Comment by mp911de** [comment]
Actually, `@RestResource` is marked as `@Inheritable` so `BaseResourceRepository<T, ID> extends PagingAndSortingRepository<T, ID>` should actually work. We should check that type erasure (`T extends BaseEntity`) doesn't interfere here.

**Comment by gregturn** [comment]
I wrote this...

```java
	class BaseEntity {}

	@NoRepositoryBean
	interface BaseThatExtendsPagingAndSupportingAndHidesDelete<T extends BaseEntity, ID extends Serializable>
			extends PagingAndSortingRepository<T, ID> {

		@Override
		@RestResource(exported = false)
		void delete(T t);
	}

	class Contact extends BaseEntity {}

	interface ContactRepository extends BaseThatExtendsPagingAndSupportingAndHidesDelete<Contact, Long> {}
```

...and tested with this:

```java
	@Test
	public void deleteIsHidden() {

		SupportedHttpMethods supportedHttpMethods = getSupportedHttpMethodsFor(
				BaseThatExtendsPagingAndSupportingAndHidesDelete.class);

		assertMethodsSupported(supportedHttpMethods, ITEM, false, DELETE);

		supportedHttpMethods = getSupportedHttpMethodsFor(ContactRepository.class);

		assertMethodsSupported(supportedHttpMethods, ITEM, false, DELETE);
	}
```

It passes. This is works in pure Java, so I'm curious if this is a Groovy-specific issue.

**Comment by gregturn** [comment]
We have code that tests some quirks of Groovy and simulate Groovy types by merely extending `GroovyObject`. I adjusted this test case like this:

```java
class BaseEntity implements GroovyObject {

	//
	// The following fields don't actually have to be implemented since the test cases don't
	// make any Groovy calls. This just simulates the structure of a Groovy object to
	// verify proper handling.
	//

	@Override
	public Object invokeMethod(String s, Object o) {
		return null;
	}

	@Override
	public Object getProperty(String s) {
		return null;
	}

	@Override
	public void setProperty(String s, Object o) {}

	@Override
	public MetaClass getMetaClass() {
		return null;
	}

	@Override
	public void setMetaClass(MetaClass metaClass) {}
}
```

It works just the same. 

Do you have a test case or output showing more details of what's not working?

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
