### ISSUE TITLE
Interceptor called twice per request in spring-data-rest.

### ISSUE THREAD

**Issue by andriymahats** [spring-projects/spring-data-rest#1969]
On spring-boot 2.4.x the interceptor is called twice.

Please check this test app to reproduce the bug.
https://github.com/andriymahats/spring-boot-test-proj

Thanks.

**Comment by gregturn** [comment]
Resolved via https://github.com/spring-projects/spring-data-rest/commit/4d7daa9f6e0b2edbf526b35fa330be392e67507b.

Duplicates #1955.

**Comment by orubel** [comment]
I believe (from just now reading the fix) that this is also effecting SimpleUrlHandlerMapping; Noticed this hasn't been added to SimpleUrlHandlerMapping and I am seeing this error:

		SimpleUrlHandlerMapping mapping = new SimpleUrlHandlerMapping();
		mapping.registerHandlers(urlMap)
		mapping.setUrlMap(urlMap);
		mapping.setOrder(1);
		mapping.setInterceptors(new Object[]{ new ApiInterceptor() })
		mapping.setApplicationContext(context);
		mapping.initApplicationContext()
