### ISSUE TITLE
Current documentation mentions removed RepositoryRestConfigurerAdapter

### ISSUE THREAD

**Issue by fapdash** [spring-projects/spring-data-rest#1983]
The current documentation mentions the `RepositoryRestConfigurerAdapter`, which apparently was included in earlier version, but has been removed. (https://docs.spring.io/spring-data/rest/docs/current/reference/html/#validation)

**Comment by gregturn** [comment]
Spring Data REST 3.3.x had `RepositoryRestConfigurerAdapter`, so no need to backport to that version (or earlier).

**Comment by jh0l** [comment]
WHY WAS IT REMOVED
