### ISSUE TITLE
Patch on resource with subresources  leads to error 

### ISSUE THREAD

**Issue by ajobra76** [spring-projects/spring-data-rest#2015]
In the newest spring boot release 2.5.0 a patch to a resource with subresources of type
{...
foos: [  "http://localhost:8080/api/foos/155271{?projection}"]
...}

leads to MismatchedInputException: Cannot construct instance of `com.entities.Foo` (although at least one Creator exists): no String-argument constructor/factory method to deserialize from String value ('http://localhost:8080/api/foos/155271{?projection}')

In previous releases this was possible...

**Comment by mp911de** [comment]
If you would like us to spend some time helping you to diagnose the problem, please spend some time describing it and, ideally, providing a [minimal sample](https://stackoverflow.com/help/mcve) that reproduces the problem.

**Comment by ajobra76** [comment]
[testrepository-testPatch@992e8389822.zip](https://github.com/spring-projects/spring-data-rest/files/6615182/testrepository-testPatch%40992e8389822.zip)

If you run the attached minimal sample and do PATCH http://localhost:8080/api/bars/1
Content-Type: application/hal+json

{"foos": ["http://localhost:8080/api/foos/2"]}

you should see the Exception. The Patch call worked in previous Spring versions.

**Comment by sullrich84** [comment]
This looks similar to #2023. As far as I can tell, the responsible converter does not support `application/hal+json` by default. Can you check if using one of these `content-types` solves your issue?

- application/schema+json
- application/json-patch+json
- application/merge-patch+json
- application/x-spring-data-verbose+json
- application/x-spring-data-compact+json

**Comment by vgarmash** [comment]
@mp911de 
I also got this error after upgrade. I am using Spring Data Rest with MongoDB and in some cases I use @DbRef to associate 2 entities. With Spring Data Rest 2.4.4 everything worked fine: to create or update the entity with @DbRef field I had to provide URL. For example. 
Assume we have these 2 classes:

```
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import lombok.Data;
import lombok.EqualsAndHashCode;
import org.springframework.data.annotation.TypeAlias;
import org.springframework.data.mongodb.core.mapping.DBRef;
import org.springframework.data.mongodb.core.mapping.Document;

import javax.validation.constraints.NotNull;

@Document(collection = "calendars")
@TypeAlias("calendar")
@Data
@EqualsAndHashCode(callSuper = true)
@JsonIgnoreProperties(ignoreUnknown = true)
public class Calendar implements Serializable, Cloneable {

    @Id
    @Schema(accessMode = Schema.AccessMode.READ_ONLY)
    private String id;

    private String name;

    @NotNull
    @DBRef
    private Employee owner;

    private boolean isDefaultCalendar;
}
```

```
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import lombok.Data;
import lombok.EqualsAndHashCode;
import org.springframework.data.annotation.TypeAlias;
import org.springframework.data.mongodb.core.index.IndexDirection;
import org.springframework.data.mongodb.core.index.Indexed;
import org.springframework.data.mongodb.core.mapping.Document;

import javax.validation.constraints.NotBlank;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

@Document(collection = "employees")
@TypeAlias("employee")
@Data
@EqualsAndHashCode(callSuper = true)
@JsonIgnoreProperties(ignoreUnknown = true)
public class Employee implements Serializable, Cloneable {

    @Id
    @Schema(accessMode = Schema.AccessMode.READ_ONLY)
    private String id;

    @NotNull
    private EmployeeTitle employeeType;

    @NotBlank
    @Size(min = 2, max = 70)
    @Indexed(direction = IndexDirection.ASCENDING)
    private String firstName;

    @Size(min = 2, max = 70)
    private String middleName;

    @NotBlank
    @Size(min = 2, max = 70)
    @Indexed(direction = IndexDirection.ASCENDING)
    private String lastName;

    public enum EmployeeTitle {
        COACH, NURSE
    }
}
```

Assume that we have Employee Bob with Id=1234567890. To create Calendar for him, we need to do the following:

```
POST http://localhost:8080/calendars
{
  "name": "Bob's calendar",
  "owner": "http://localhost:8080/employees/1234567890"
}
```


This code worked fine with Spring Data Rest 2.4.4, but started failing with error in 2.5.0 saying that it can't deserialize Employee from "http://localhost:8080/employees/1234567890". All unit tests for POST, PUT and PATCH operations started failing the same way.

**Comment by sullrich84** [comment]
@vgarmash @ajobra76 can you check if the error also occurs when you send the payload as content-type `application/schema+json`? I assume the internal `halJacksonHttpMessageConverter` is bugged.

**Comment by odrotbohm** [comment]
This looks similar to what's described in #2022 which is resolved in recent Spring Boot 2.5.12. Would you mind checking whether the latest Spring Boot release solves the issue?

**Comment by ajobra76** [comment]
I can confirm that in the latest release the issue is solved.

**Comment by odrotbohm** [comment]
Awesome, thanks!
