### ISSUE TITLE
All buttons other than GET are disabled

### ISSUE THREAD

**Issue by onacit** [spring-projects/spring-data-rest#2017]
With Spring Boot 2.5.0, all buttons in HAL Explorer except GET are disabled.

Is there any significant changes for that? Thanks.

**Comment by mp911de** [comment]
If you would like us to spend some time helping you to diagnose the problem, please spend some time describing it and, ideally, providing a [minimal sample](https://stackoverflow.com/help/mcve) that reproduces the problem.
