### ISSUE TITLE
Spring security makes the Spring data rest to treat the URI of the reference target as a String

### ISSUE THREAD

**Issue by tio-plato** [spring-projects/spring-data-rest#2022]
I have 2 classes ```House``` and ```Service```with many-to-many relationship:

```java
@Data
@Entity
public class House implements Serializable
{
	@Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    private String title = "";

    @ManyToMany(targetEntity = Service.class, cascade = {CascadeType.PERSIST, CascadeType.REFRESH})
    @JoinTable(...)
    private Set<Service> services;
}
```
```java
@Data
@Entity
public class Service implements Serializable
{
	@Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    private String name= "";

    @JsonProperty(access = JsonProperty.Access.WRITE_ONLY)
    @ManyToMany(mappedBy = "services", fetch = FetchType.LAZY)
    private Set<House> houses;
}
```

If I want to create a house with services 1 and 2, I will post to ```/houses``` with request body is like:
```json
{
    "title": "title1",
    "services": [
        "/services/1",
        "/services/2"
    ]
}

```
The endpoint automatically generated by spring data rest can handle the URI of services and create relationships in the database.
But when I imported spring-boot-starter-security, it throws ```HttpMessageNotReadableException```:
```
2021-06-09 02:49:46.683  WARN 2192 --- [io-17698-exec-6] .m.m.a.ExceptionHandlerExceptionResolver : Resolved [org.springframework.http.converter.HttpMessageNotReadableException: Could not read payload!; nested exception is com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot construct instance of `com.a.project.entity.Service` (although at least one Creator exists): no String-argument constructor/factory method to deserialize from String value ('/services/1')
 at [Source: UNKNOWN; line: -1, column: -1] (through reference chain: com.isep.project.entity.House["services"]->java.util.HashSet[0])]

```

It seems that Spring treats the services in the request body as ```String```, and I have to write it like this:
```json
{
    "title": "title1",
    "services": [
        {"id":1},
		{"id":2}
    ]
}

```
I'm a little confused as to why this is happening and what I should do to continue to allow Spring to treat the services as URI while importing spring-security?

Version:
java: tried with 1.8 and 15
spring: tried with 2.4.5 and 2.5.0

**Comment by sullrich84** [comment]
This looks very similar to #2023. Can you try to use one of the following `content-types` to check if this solves your issue?

- application/schema+json
- application/json-patch+json
- application/merge-patch+json
- application/x-spring-data-verbose+json
- application/x-spring-data-compact+json

**Comment by mp911de** [comment]
Can you help us by providing a [minimal sample](https://stackoverflow.com/help/mcve) that reproduces the problem? Right now we need to understand how Spring Security plays into Jackson's deserialization.

**Comment by tio-plato** [comment]
I'm sorry I was so busy recently and I had no time to check this issue.
I recently retested and found that what I thought about the cause of the error was wrong, in fact it was not related to spring security, it was caused by spring boot 2.5 (Similar to #2023 ）

[Here is a minimal sample](https://github.com/tio-plato/minimal-simple-2022)

**Comment by odrotbohm** [comment]
This looks to be working with the latest Spring Boot 2.5.12.
