### ISSUE TITLE
Testing with MockMVC

### ISSUE THREAD

**Issue by mikebski** [spring-projects/spring-data-rest#2029]
Is there any documentation for testing this with MockMVC? Everything works fine for me until I start trying to put resources of type `Content-Type:text/uri-list` at endpoints.

I'm sure there is some configuration needed, I get a 404 for the related resource endpoints, but I can't find documentation about it...

**Comment by odrotbohm** [comment]
I'Ve transferred the issue. Would you mind elaborating on the actual problem statement?

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
