### ISSUE TITLE
RepresentationModelProcessor of Projection called

### ISSUE THREAD

**Issue by 1-alex98** [spring-projects/spring-data-rest#2039]
I have
```
RepresentationModelProcessor<EntityModel<InternalNetworkMembership>>
```
to add Links to the `InternalNetworkMembership`
and a projection on this Entity
```
@Projection(name = "inlineNetwork", types = InternalNetworkMembership.class)
public interface InlineNetworkNameProjection
{
    @Value("#{target.internalNetwork.name}")
    String getInternalNetworkName();
}
```
And because for me unknow reasons SDR does not support allowing to choose the projection for collections I set:
```
@RepositoryRestResource(...
                        excerptProjection = InlineNetworkNameProjection.class)
 ```
When debugging 
```
RepresentationModelProcessor<EntityModel<InternalNetworkMembership>>
```
is never called but if I register
```
RepresentationModelProcessor<EntityModel<InlineNetworkNameProjection>>
```
that is called with a proxy conatining my `InternalNetworkMembership`.

**Comment by odrotbohm** [comment]
What is the actual problem this is causing? What you see is expected as the projection is implemented using a proxy pointing to the actual entity. This is to be able to resolve `getInternalNetworkName()` according to the SpEL expression you have defined.

You should see the different `RMP`s called depending on whether a projection is actually returned or the pure entity.

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by 1-alex98** [comment]
Yes the more I think about it the less sense makes by bug report.
