### ISSUE TITLE
@LastModifiedDate does not support OffsetDateTime properties

### ISSUE THREAD

**Issue by alienisty** [spring-projects/spring-data-rest#2040]
We use OffsetDateTime for our auditing data, but a property of such type annotated with @LastModifiedDate fails to convert it to instant because the converters in Jsr310Converters do not provide a converter from OffsetDateTime to Date.
The other problem is that the annotation is only supported on entity properties or their getters and is allowed but with no effect on methods that are not properties getters.
For example, we'd like to add the Last-Modified-Date header as a trait, using an interface, for example:
```java
public interface LastModifiedAware {
  @LastModifiedDate
  public TemporalAccessor getLastModifiedDate();
}

public class MyEntity implements LastModifiedAware {
  ...
  private OffsetDateTime lastModified;
  ...
 
  public OffsetDateTime getLastModifiedDate() {
    return lastModified;
  }
}
```

The above does not work out of the box so we customise the AuditableBeanWrapperFactory by delegating to MappingAuditableBeanWrapperFactory for the "standard" case and to a custom implementation to support our desired mechanism.

Recently though, as reported in #1981, RepositoryRestMvcConfiguration can no longer be subclassed, so we would like to either restore the previous support, or add the ability to obtain the desired behaviour.

**Comment by odrotbohm** [comment]
We can certainly introduce a callback on `RepositoryRestConfigurer` but be advised that using time-zoned dates in your domain model is begging for trouble *unless* the backing data store has explicit support for that. I am not aware that any of the backends of the Spring Data modules actually have that. That's the primary reason we do not natively support those types in any of our mapping subsystems in the first place.

**Comment by alienisty** [comment]
Using 2021.1.0-SNAPSHOT I tried using the new customization mechanism and it all works as expected.
