### ISSUE TITLE
DelegatingHandlerMapping does not implement/override getPatternParser()

### ISSUE THREAD

**Issue by dhoeppe** [spring-projects/spring-data-rest#2054]
The `DelegatingHandlerMapping` in 3.5.x does not implement/override `getPatternParser()` from `MatchableHandlerMapping`.

This prevents the `DelegatingHandlerMapping` from being initialized as `PathPatternMatchableHandlerMapping` in `initPathPatternMatchableHandlerMappings()` in `HandlerMappingIntrospector`.

I am not sure of all the implications this has, but I know that this disables the `@CrossOrigin` support.

**Comment by odrotbohm** [comment]
It looks like the fix for #2007 never actually made it into the 3.5.x branch. Should be an easy fix.
