### ISSUE TITLE
[HAL Explorer] All buttons except GET are disabled by default

### ISSUE THREAD

**Issue by djkeh** [spring-projects/spring-data-rest#2060]
Hi,

Starting from Spring Boot 2.5, all buttons in HAL Explorer except GET are disabled at the first time.

### Reproducing the problem

1. Initialize Spring Boot project at https://start.spring.io/ including following dependencies:
	* spring-boot-starter-data-jpa
	* spring-boot-starter-data-rest
	* spring-boot-starter-web
	* spring-data-rest-hal-explorer
	* h2 database
2. Make a single entity class and its repository implementing `JpaRepository`
3. Run Spring Boot application
4. See HAL explorer web page

### The cause of this problem

According to toedter/hal-explorer#28, This is intended behavior for hal explorer as the data rest api responds with the `Content-Type: application/hal-forms+json`. However, it seems we don't have a workaround for this problem like forcing response content type to `application/hal+json`. We have a spring boot property named `spring.data.rest.default-media-type`, but it takes no effect.

We have to give some option for HAL explorer to request certain content-type of the api endpoints like forcing `Accept` header, so that the HAL explorer recognizes the endpoint properly and shows every button like it used to do before spring boot version 2.5.

This is first mentioned in #2017 

Thanks.

**Comment by djkeh** [comment]
Actually, I got a workaround to solve this problem at toedter/hal-explorer#28#issuecomment-917588846

**Comment by odrotbohm** [comment]
Not the easiest thing to solve conceptually, but I think I've got a fix. Here's what's going on:

17538c65d7c18edf2aaaca8b565f04545033cbaf introduced general support for HAL FORMS for Spring Data REST. I.e. we would support requests asking for HAL FORMS to see HAL FORMS using the serializers available in Spring HATEOAS. However, we would not actually add any affordances yet that, with HAL FORMS, would result in `_templates` being rendered. That means, if a client now requests HAL FORMS (as the HAL Explorer does), the registered `HttpMessageConverter` will kick in and render a plain HAL document as there are simply no `_templates` to be rendered.

I have a fix available that adapts the `Content-Type` header depending on whether affordances (and thus `_templates`) are present whenever HAL FORMS is supposed to be rendered. If none can be found, we either adapt the header to either `application/hal+json` or even `application/json` depending on the `Accept` header arrangement given. If none match, we reject the request with `406 Not Acceptable`.

**Comment by Ickbinet** [comment]
This issue is solved by https://github.com/toedter/hal-explorer/issues/39

**Comment by odrotbohm** [comment]
The issue was actually solved by the fix implemented and shipped with Spring Data REST 3.5.5 as can be seen from the related commits and fix version attribute. I'd like to sincerely ask to refrain from statements about the state of issues considering work that you're not involved with. It's highly confusing to users if other users comment as if they were involved in the fixes. Thanks!
