### ISSUE TITLE
Accessing the unlinked object in the HandleAfterLinkDelete handler method

### ISSUE THREAD

**Issue by aaclan-ebi** [spring-projects/spring-data-rest#2092]
I couldn't find any documentation regarding this but I wonder if it is possible to access the unlinked object in the link event handler? Upon debugging, it is a proxy object but why pass it as a parameter if it's not accessible.

```
@HandleAfterLinkDelete
public void handleAfterUnlinked(Entity entity, Object unlinked) {
    //unlinked is a proxy object
}
```
or even in the before handler

```
@HandleBeforeLinkDelete
public void handleBeforeUnlinked(Entity entity, Object unlinked) {
    //unlinked is a proxy object
}
```

**Comment by schauder** [comment]
Please provide a [Minimimal Reproducable Example](https://stackoverflow.com/help/minimal-reproducible-example), preferable as a Github repository. Make sure to include the database, either as an in memory database or if that is not possible using [Testcontainers](https://www.testcontainers.org/).

Until that is ready, providing a full stacktrace might make it possible to decide what is going on.

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.
