### ISSUE TITLE
Jpa pageable sort not support List Type PersistentProperty

### ISSUE THREAD

**Issue by senekis316** [spring-projects/spring-data-rest#2109]
Hi,

When use sort by List PersistentProperty, found it not work!

Example:

(1) private List<OrderEntity> orders
use url parameter : sort=quotations.id,desc
not support

(2) private OrderEntity order
use url parameter : sort=quotation.id,desc
support

------------------------------------------------------------

I looked at the source code:

JacksonMappingAwareSortTranslator 

public TypedSegment next(PersistentProperty<?> persistentProperty) {

	Assert.notNull(persistentProperty, "PersistentProperty must not be null!");

	return new TypedSegment(this, persistentEntities.getPersistentEntity(persistentProperty.getType()));
}

---------------------------------------------------------------------------

When use List<OrderEntity>, persistentProperty.getType() result List 

I found persistentProperty.getTypeInformation().getActualType() can return orderEntity

I don't know if this is ok, whether it can be modified in this way?

**Comment by schauder** [comment]
When loading a list of entities, what would it even mean to have it sorted by some multivalued field?
I don't think we should support sorting by such fields.
