### ISSUE TITLE
How to achieve bi-directional associations from ManyToMany associated Entities in Spring Data Rest

### ISSUE THREAD

**Issue by PradeepMaiyaVersion1** [spring-projects/spring-data-rest#2121]
Currently, I'm learning Spring Data Rest, where I am having two Entities "Application" &  "Component" where both are having "@ManyToMany" associations present between them built using Spring Data Rest.

**Application Entity**
```
@Entity
@Table(name = "application")
@Getter
@Setter
@ToString
public class Application {
---
---
    @ManyToMany(mappedBy = "applications", cascade = CascadeType.PERSIST)
	@JsonIgnore
	private List<Component> components = new ArrayList<Component>();
	
    //Helper methods for bi-directional mapping
    public void addComponent(Component component) {
        components.add(component);
        component.getApplications().add(this);
    }
 
    public void removeComponent(Component component) {
        components.remove(component);
        component.getApplications().remove(this);
    }
}
```

**Component Entity**
```
@Entity
@Table(name = "component")
@Getter
@Setter
@ToString
public class Component{
---
---
    @ManyToMany(cascade = CascadeType.PERSIST)
    @JoinTable(name = "component_application", 
      joinColumns = @JoinColumn(name = "component_id", referencedColumnName = "id"), 
      inverseJoinColumns = @JoinColumn(name = "application_id",referencedColumnName = "id"))
    @JsonIgnore
    private List<Application> applications = new ArrayList<Application>();
}
```

while testing associated APIs, APIs associated with Component Entity (owner class) is working 
**Component associated API**
```
curl -X PUT "https://ENVIRONMENT.com/components/1/applications" -H "accept: */*" -H "Content-Type: text/uri-list" -d BODY_LIST
```
with body
```
https://ENVIRONMENT.com/applications/1
https://ENVIRONMENT.com/applications/12
```

But when I tried to create bi-directional associations from Application Entity (managed class) association APIs are not working, getting 204 for the PUT API call but nothing got associated when GET call is done.
**Application association API**
```
curl -X PUT "https://ENVIRONMENT.com/applications/1/component" -H "accept: */*" -H "Content-Type: text/uri-list" -d BODY_LIST
```
with body
```
https://ENVIRONMENT.com/components/1
https://ENVIRONMENT.com/components/2
```

I tried adding custom add, remove methods in a managed class which is "Application Entity" here, still the same issue. Please let me know where I'm missing out.

**Comment by odrotbohm** [comment]
You need to design your domain types in a way that both sides of the association are kept in sync when the collections are manipulated. In general, we recommend to avoid bi-directional relationships as they are a ubiquituous source of problems because keeping both entities in sync is notoriously hard to get right.

I am inclined to close this as it's more of a general JPA class design question, nothing Spring Data REST specific in particular.

**Comment by PradeepMaiyaVersion1** [comment]
> You need to design your domain types in a way that both sides of the association are kept in sync when the collections are manipulated. In general, we recommend to avoid bi-directional relationships as they are a ubiquituous source of problems because keeping both entities in sync is notoriously hard to get right.
> 
> I am inclined to close this as it's more of a general JPA class design question, nothing Spring Data REST specific in particular.

Can you please let me know how can I design classes in order to achieve two way association

**Comment by odrotbohm** [comment]
Unfortunately, I can't. We recommend avoiding them as they introduce  dependency cycles that are fundamentally problematic design. That said, you'll surely find numerous examples on the internet how to implement them for JPA.
