### ISSUE TITLE
HalFormsAdaptingResponseBodyAdvice throws NullPointerException when response would be "304 Not Modified"

### ISSUE THREAD

**Issue by vierbergenlars** [spring-projects/spring-data-rest#2123]
This piece of code to get the affordances may result in a NullPointerException in case `body` is null.

https://github.com/spring-projects/spring-data-rest/blob/3eed1c26301d1ab77bd82ed702d9650e0105e2a1/spring-data-rest-webmvc/src/main/java/org/springframework/data/rest/webmvc/config/HalFormsAdaptingResponseBodyAdvice.java#L77-L78

In the [`ResponseBodyAdvice` interface from spring-webmvc](https://github.com/spring-projects/spring-framework/blob/5119aafe4f2f807b1ef0e6f16401c4f9c155123a/spring-webmvc/src/main/java/org/springframework/web/servlet/mvc/method/annotation/ResponseBodyAdvice.java#L52-L67), the `body` parameter is annotated as `@Nullable`, an annotation that was not taken into account in  `HalFormsAdaptingResponseBodyAdvice`.

While developing a spring-data-rest application, I encountered a case where the body might be null, in the case that a `304 Not Modified` response is being sent.
A Not Modified status can be sent by spring-data-rest when there is an entity with a `@LastModifiedDate`-annotated property, and an `If-Modified-Since` request header is sent by the client.
In case the date from `If-Modified-Since` is after the date from the `@LastModifiedDate` property, the `304 Not Modified` response is sent with a `null` body, resulting in a `NullPointerException` from `HalFormsAdaptingResponseBodyAdvice`, which always results in an Internal Server Error.

**Comment by odrotbohm** [comment]
This should be fixed in all maintained snapshots (4.0-3.5.x).
