### ISSUE TITLE
SimpleUrlHandlerMapping is calling HandlerInterceptor twice (like in #1969)

### ISSUE THREAD

**Issue by orubel** [spring-projects/spring-data-rest#2129]
see #1969. This was fixed but not for SimpleUrlHandlerMapping.

I believe (from just now reading the fix) that this is also effecting SimpleUrlHandlerMapping; Noticed this hasn't been added to SimpleUrlHandlerMapping and I am seeing this error as well. Tried troubleshooting this from every angle but to no avail until I saw this.

	SimpleUrlHandlerMapping mapping = new SimpleUrlHandlerMapping();
	mapping.registerHandlers(urlMap)
	mapping.setUrlMap(urlMap);
	mapping.setOrder(1);
	mapping.setInterceptors(new Object[]{ new ApiInterceptor() })
	mapping.setApplicationContext(context);
	mapping.initApplicationContext()

My code is here (minus external config files): https://github.com/orubel/spring-boot-starter-beapi

**Comment by odrotbohm** [comment]
This needs to be filed against Spring Framework as that's where `SimpleUrlHandlerMapping` actually lives.
