### ISSUE TITLE
Migration from 2.3.2 vs 3.5.2

### ISSUE THREAD

**Issue by mbarbin-groupeseb** [spring-projects/spring-data-rest#2200]
Hello,

We are migrating an application using SDR from version 2.3.2 to version 3.5.2 (which correspond to Springboot 2.5.2).
The entity layer is based on spring-data-mongodb but I don't think this is too relevant for our use case, it would be the same with another one.

On the old version of the application, the legacy code was overriding SDR configuration by extending the `RepositoryRestMvcConfiguration` and overriding the bean definition for `persistentEntityJackson2Module` to remove serializerModifier and deserializerModifier.

```
@EnableWebMvc
@EnableSpringDataWebSupport
@Configuration
class RepositoryConfiguration extends RepositoryRestMvcConfiguration {

...
...


  @Bean
  @Override
  protected Module persistentEntityJackson2Module() {
     // Remove existing Ser/DeserializerModifier because Spring data rest expect linked resources to be in href form. Our platform is not tailored for it yet
     return ConverterHelper.configureSimpleModule((SimpleModule) super.persistentEntityJackson2Module())
        .setDeserializerModifier(null)
        .setSerializerModifier(null);
}
```

It was to avoid having to process relations as href link when posting or reading entities, as we just pass the plain POJO instead of the href and we persist it manually before the entity.

We would like to find a way to continue using model instead of href for relation as changing all our process would be way too costly, induce many breaking changes and we are not in charge of our consumers.

Any idea how to do it ? We removed our class which was extending `RepositoryRestMvcConfiguration` to use the new `
RepositoryRestConfigurer` but I didn't find any way to customize the `persistentEntityJackson2Module` in it. 

Thanks a lot ! If you need more information about our configuration, please tell me :-)

**Comment by odrotbohm** [comment]
As described in the [docs](https://docs.spring.io/spring-data/rest/docs/current/reference/html/#getting-started.configuration), customization options have been moved into the `RepositoryRestConfigurer` interface. In this, you'll find a `….configureJacksonObjectMapper(…)` method to customize the Jackson `ObjectMapper`.
