### ISSUE TITLE
Size parameter to pull all records in the first page

### ISSUE THREAD

**Issue by prasannabalaraman** [spring-projects/spring-data-rest#2205]
Hello,

The default value for size is 20 and it is possible to change it by passing size parameter in url. 

/employees?size=50 

Is there a way to pull all the records by passing any value in the url? 

maybe like : /employees?size=-1

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by prasannabalaraman** [comment]
I agree to your point about huge data leads to OOM. Just wanted to see whether any special parameter to pull all records just in case.

**Comment by prasannabalaraman** [comment]
This can be closed
