### ISSUE TITLE
Adding summary/metrics part of the response

### ISSUE THREAD

**Issue by prasannabalaraman** [spring-projects/spring-data-rest#2206]
I am looking to add a metrics json to the default findById and findAll operations. I would need to execute a native query and embed the json response part of the findById and findAll apis.

Is it possible to do achieve this without writing custom controller in spring data rest?

Appreciate your help.

**Comment by christophstrobl** [comment]
If you would like us to spend some time helping you to diagnose the problem, please spend some time describing it. Right now, we struggle to understand what you want to achieve.

**Comment by prasannabalaraman** [comment]
I am using Spring data rest and my repository classes are extending PagingAndSortingRepository interface. Spring data rest provides endpoints for findById and findAll repo methods which populates all the fields available in the respective table. 

My requirement is to run another query to generate a summary statistics and append that part of findById and findAll response in json format

My workaround implementation:
I have created a @Transient field (for eg: private Metrics metrics) in the entity class. In getMetrics(), I am executing a native query to generate the required metrics and setting it to this transient variable. This automatically appends metrics json to the findById and findAll responses.

I am trying to understand a better approach than the above workaround.
