### ISSUE TITLE
Endpoints for count and exists with predicate

### ISSUE THREAD

**Issue by j1myx** [spring-projects/spring-data-rest#2223]
Ideally, the RepositoryEntityController or RepositorySearchController controller also exposes two additional endpoints for count and exists, on which you can work with predicates. In this way, the quantities can be obtained and verify that there is an item:

Use Examples:

http://localhost:8080/users/count?profile=ADMIN

http://localhost:8080/users/exists?profile=ADMIN

**Comment by odrotbohm** [comment]
Spring Data REST's goal is not to expose every method available on `CrudRepository` but rather implement established patterns in designing collection-like HTTP resources. Exposing fine-grained resources for a count or exists checks ar no such patterns.
