### ISSUE TITLE
JSON Patch uses org.springframework.core.convert.support.DefaultConversionService#getSharedInstance

### ISSUE THREAD

**Issue by buckett** [spring-projects/spring-data-rest#2233]
When a JSON patch request is made the paths are parsed and converted into `org.springframework.data.rest.webmvc.json.patch.SpelPath` when values are then replaced the SpEL paths are then evaluated using a `org.springframework.expression.spel.ExpressionState` and this uses a `org.springframework.expression.spel.support.SimpleEvaluationContext` which then ended up using a `org.springframework.expression.spel.support.StandardTypeConverter`, this in turn uses `org.springframework.core.convert.support.DefaultConversionService#getSharedInstance` for it's conversion service.

This works for simple cases (Strings and Ints), but the `DefaultConversionService` doesn't have complete support for Java 8 date and time classes and the JavaDoc on the method recommends that the service should only be used as a fallback.

There doesn't seem to be a way to override the `ConversionService` that is used when evaluating SpEL paths in JSON Patch files and it doesn't seem to be possible to add additional converters to the `DefaultConversionService`.

One solution might be to have `org.springframework.data.rest.webmvc.json.patch.SpelPath.TypedSpelPath#CONTEXT` setable at runtime and therefore allow a `EvaluationContext` with a different conversion service to be used.

**Comment by odrotbohm** [comment]
Would you mind zooming out a bit and describe a user level problem this results in?

**Comment by odrotbohm** [comment]
Nevermind, your test case has all I need to think about this.

**Comment by buckett** [comment]
Just to check I wasn't missing anything I did also create a test project showing the issue: https://github.com/buckett/json-patch-test

**Comment by buckett** [comment]
## Failing with the BOM
I tried added `<spring-data-bom.version>4.0.3-SNAPSHOT</spring-data-bom.version>` to the Spring Boot app and then it tries to download `org.springframework.data:spring-data-bom:pom:4.0.3-SNAPSHOT` but fails.
I tried adding the Spring specific snapshot repository:
```
	<repositories>
		<repository>
			<id>spring-snapshot</id>
			<name>Spring Snapshot Repository</name>
			<url>https://repo.spring.io/snapshot</url>
			<snapshots>
				<enabled>true</enabled>
			</snapshots>
		</repository>
	</repositories>
```

but this doesn't appear to help and I can't see any similar versions in the UI: https://repo.spring.io/ui/packages/gav:%2F%2Forg.springframework.data:spring-data-bom?name=spring-data-bom&type=packages

## Pulling in 4.0.x branch

Instead I've tried pulling `<spring-data-bom.version>2022.0.3-SNAPSHOT</spring-data-bom.version>` and this seems to depend on `4.0.3-SNAPSHOT` after a bit of messing about (`mvn dependency:purge`) I have it downloading the latest artifacts and the fix looks good, in my test project after creating a person:
```
## Create a person
POST http://localhost:8080/persons
Content-Type: application/json

{
  "id": 1,
  "name": "Test",
  "birthday": "2000-01-01"
}
```
I then attempted to patch the `birthday` field:
```
PATCH http://localhost:8080/persons/1
Content-Type: application/json-patch+json

[
  {"op": "replace", "path": "/birthday", "value": "1980-02-20"}
]
```
it worked (HTTP 204) 👍 and double checking the person now has the new birthday.

**Comment by odrotbohm** [comment]
Yeez, I messed the version numbers up: it's got to be `2022.0.3-SNAPSHOT` for the `spring-data-bom.version` property. That should give you `4.0.3-SNAPSHOT` of SD REST. Looks like you got it working nonetheless. So looking forward to the release! 🥳
