### ISSUE TITLE
Issue accessing property via hateoas link when lazy loading is active. 

### ISSUE THREAD

**Issue by saschakr** [spring-projects/spring-data-rest#2234]
I have following class Note.java
```java
@Entity
public class Note {
    //.. id
    @ManyToOne(fetch = FetchType.LAZY)
    private Author author;
}
```

When accessing a element via `GET /notes/1` I receive follwing response.

```json
{
  "title" : "Note#1",
  "text" : "Content#1",
  "_links" : {
    "self" : {
      "href" : "http://localhost:8080/notes/1"
    },
    "note" : {
      "href" : "http://localhost:8080/notes/1"
    },
    "author" : {
      "href" : "http://localhost:8080/notes/1/author"
    }
  }
}
```

But when doing `GET http://localhost:8080/notes/1/author` I get following exception: 

```
com.fasterxml.jackson.databind.exc.InvalidDefinitionException: No serializer found for class org.hibernate.proxy.pojo.bytebuddy.ByteBuddyInterceptor and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS) (through reference chain: org.springframework.data.rest.webmvc.json.PersistentEntityJackson2Module$PersistentEntityResourceSerializer$1["content"]->github.skreutz.model.Author$HibernateProxy$XZxIw8Hs["hibernateLazyInitializer"])
	at com.fasterxml.jackson.databind.exc.InvalidDefinitionException.from(InvalidDefinitionException.java:77) ~[jackson-databind-2.14.1.jar:2.14.1]
```

When changing `@ManyToOne(fetch = FetchType.LAZY)` to `@ManyToOne(fetch = FetchType.EAGER)` this endpoints works fine.

I created a sample project: https://github.com/saschakr/spring-boot-data-rest-example

**Comment by odrotbohm** [comment]
Do you use the [Jackson Hibernate integration](https://github.com/FasterXML/jackson-datatype-hibernate)? This should actually take care of this problem.

As a side node: `@ManyTo…` mappings are a smell as the logically don't have a place in an aggregate model. Either `Author` is an aggregate root, too. In that case, rather model the property as an identifier, optionally using `@Reference(…)` to explicitly declare the target aggregate type. The latter shouldn't be needed if you use dedicated identifier types (i.e. we can find out that e.g. `AuthorId` is the identifier type of `Author`. If `Author` is *not* an aggregate root but a simple entity, then the many-to-relationship doesn't make sense as aggregates own their entities to be able to control invariants.

**Comment by lucheng82** [comment]
> Do you use the [Jackson Hibernate integration](https://github.com/FasterXML/jackson-datatype-hibernate)? This should actually take care of this problem.
> 
> As a side node: `@ManyTo…` mappings are a smell as the logically don't have a place in an aggregate model. Either `Author` is an aggregate root, too. In that case, rather model the property as an identifier, optionally using `@Reference(…)` to explicitly declare the target aggregate type. The latter shouldn't be needed if you use dedicated identifier types (i.e. we can find out that e.g. `AuthorId` is the identifier type of `Author`. If `Author` is _not_ an aggregate root but a simple entity, then the many-to-relationship doesn't make sense as aggregates own their entities to be able to control invariants.

In the springboot3.x version, the many-to-one relationship does not have lazy loading, and printing SQL finds that it triggers a secondary query, so I tried to explicitly declare lazy loading, but I also encountered this problem. I tried @odrotbohm  solution, but it didn't work.

**Comment by odrotbohm** [comment]
We actually already register this module with a slightly different configuration, but the lazy loading forcibly enabled in `Jackson2DatatypeHelper`. So, enabling this should be a matter of adding the Jackson Hibernate integration library on the classpath.

**Comment by saschakr** [comment]
@jacko9et jackson-datatype-hibernate6 was released with version 2.15.0 (23-Apr-2023)

Thanks for the answers @odrotbohm and @jacko9et

Following works for me: 

Add `jackson-datatype-hibernate6`

    <dependency>
        <groupId>com.fasterxml.jackson.datatype</groupId>
        <artifactId>jackson-datatype-hibernate6</artifactId>
        <version>2.15.0</version>
    </dependency> 

Register hibernate 6 module

    @Autowired
    void configureObjectMapper(final ObjectMapper mapper) {
        Hibernate6Module hibernate6Module = new Hibernate6Module();
        hibernate6Module.disable(Hibernate6Module.Feature.USE_TRANSIENT_ANNOTATION);
        hibernate6Module.enable(Hibernate6Module.Feature.FORCE_LAZY_LOADING);
        mapper.registerModule(hibernate6Module);
    }
    
After this the provided test works as expected see commit: https://github.com/saschakr/spring-boot-data-rest-example/commit/91794fe9794d5db672d68e09059cb978865fa746

**Comment by odrotbohm** [comment]
Oh, that's nice to know. Let me take this ticket to upgrade to the H6 integration as we require that version for Spring Data JPA anyway.

**Comment by odrotbohm** [comment]
This should now work without further customization. Would you mind giving the 4.1 snapshots a try?

**Comment by saschakr** [comment]
@odrotbohm I've tried the 4.1.0-SNAPSHOT and it seems to work fine.

See commit
https://github.com/saschakr/spring-boot-data-rest-example/commit/de146740b61b8f55e8b085b0f1edb6e6ade5b0d8

Thanks for your help.

**Comment by odrotbohm** [comment]
Thanks for confirming!
