### ISSUE TITLE
Templated links are missing

### ISSUE THREAD

**Issue by logicg8** [spring-projects/spring-data-rest#2295]
Template Links in the form of /orders/{id} are missing. A client has no way to know that /order/12 is a valid link.

**Comment by logicg8** [comment]
Thank you for your response. Here is a complete sample of the problem:

build.gradle
```
plugins {
	id 'java'
	id 'org.springframework.boot' version '3.1.2'
	id 'io.spring.dependency-management' version '1.1.2'
}

group = 'com.example'
version = '1.0'

java {
	sourceCompatibility = '17'
}

repositories {
	mavenCentral()
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
	implementation 'org.springframework.boot:spring-boot-starter-data-rest'
	compileOnly 'org.projectlombok:lombok'
	annotationProcessor 'org.projectlombok:lombok'
	runtimeOnly 'com.h2database:h2'
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
}

tasks.named('test') {
	useJUnitPlatform()
}
```

In com.example package:

TaversonIssueApplication.java
```
@SpringBootApplication
public class TaversonIssueApplication {

	public static void main(String[] args) {
		SpringApplication.run(TaversonIssueApplication.class, args);
	}

}

```

User.java
```
@Entity
@Table(name="`User`")
@Data
public class User {
 
	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	private Long id;
	
	private String name;
	
}

```

UserRepository.java
```
public interface UserRepository extends CrudRepository<User, Long> {
}
```

In /src/main/resources:
```
INSERT INTO "user" (name) VALUES ('bob');
INSERT INTO "user" (name) VALUES ('sally');
```

Once application is started, a request to `http://localhost:8080/` results in:

```
{
  "_links" : {
    "users" : {
      "href" : "http://localhost:8080/users"
    },
    "profile" : {
      "href" : "http://localhost:8080/profile"
    }
  }
}
```

From this response, a client has know way of knowing that `http://localhost:8080/users/1` is a valid link. A [Traverson HAL](https://github.com/traverson/traverson-hal) client cannot follow the link from `http://localhost:8080/` to `http://localhost:8080/users/1`. This is because no templated link is provided such as ``http://localhost:8080/users/{id}`. 

I apologize if I'm overlooking a way for Spring Data REST to provide such a templated link. If not, could Spring Data REST produce the following in response to `http://localhost:8080/`:
```
{
  "_links" : {
    "users" : {
      "href" : "http://localhost:8080/users/{id}"
    },
    "profile" : {
      "href" : "http://localhost:8080/profile"
    }
  }
}
```

**Comment by odrotbohm** [comment]
This is an invalid expectation. The root resource exposes only the [links to collection URIs](https://docs.spring.io/spring-data/rest/docs/current/reference/html/#repository-resources.resource-discoverability). The link to item resources are contained in the collection resource. In your example, following the `users` link will lead you to a resource that lists both user documents and each of them containing a self link that fundamentally is the identifier for the individual documents which clients should use.

Beyond that, there's no need for a client to use templates for item resources, as it's supposed to work with full URIs anyway.

**Comment by logicg8** [comment]
Makes sense. I was looking at how [GitHub API](https://api.github.com/) represents "user_url" with https://api.github.com/users/{user}. I think the difference there is that https://api.github.com/users/ is not a valid link but https://api.github.com/users/logicg8 for example is valid. In Spring Data REST, the collection URI, https://localhost/users/, is valid.

Thank you for taking time to look at my comments and responding, and many thanks for creating an incredible and awesome project.
