### ISSUE TITLE
[FEATURE REQUEST]: Spring Data JPA Support for Apache Delta Lake

### ISSUE THREAD

**Issue by Vislesha** [spring-projects/spring-data-rest#2383]
Hi Team: Any plans to implement Spring Data JPA support for Apache Delta Lake provider.

Thanks!

**Comment by mp911de** [comment]
Correct me if I'm wrong, it looks that Apache Delta Lake is not a JPA implementation. So from that perspective, there isn't a JPA provider to build support on.

Other than that, we do not intend building another Spring Data module by our team. If you want, there's a [how-to guide](https://github.com/spring-projects/spring-data-commons/wiki/Developer-guide) explaining how you can start building a Spring Data module for your favorite technology.
