### ISSUE TITLE
`RepositoryEntityController` is incompatible with devtools

### ISSUE THREAD

**Issue by muliyul** [spring-projects/spring-data-rest#2438]
Cannot run application with devtools `org.springframework.boot:spring-boot-devtools`

>org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'repositoryEntityController' defined in class path resource [org/springframework/data/rest/webmvc/RestControllerConfiguration.class]: Could not generate CGLIB subclass of class org.springframework.data.rest.webmvc.RepositoryEntityController: Common causes of this problem include using a final class or a non-visible class

Seems like `RepositoryEntityController` is non-visible (no public modifier).

**Comment by mp911de** [comment]
Can you post the full stack trace (i.e. non-truncated)? We have quite a few package-protected types. I do not see why proxying would be necessary in a developer-facing project as you're not going to update these types.

**Comment by mp911de** [comment]
Paging @odrotbohm @marcingrzejszczak

**Comment by marcingrzejszczak** [comment]
Is this the problem with the 1.3.0 version? We've migrated tracing support to observability based support (although that logic with cglib proxies might not have been changed)

**Comment by odrotbohm** [comment]
I got this fixed by registering both Spring Data REST WebMVC and HAL Explorer to be included in the application classloader as documented [here](https://docs.spring.io/spring-boot/reference/using/devtools.html#using.devtools.restart.customizing-the-classload). I'll consult the Boot team to better understand why that is.

**Comment by odrotbohm** [comment]
We need to revert the fix for this as it causes unintended side-effects reported in GH-2442. Good news is that I have a fix for Spring Modulith, which is actually causing the issue here, coming for the next bugfix releases.
