### ISSUE TITLE
@Valid is not supported on @RepositoryRestController [DATAREST-593]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-rest#967]
**[Bob Tiernay](https://jira.spring.io/secure/ViewProfile.jspa?name=btiernay)** opened **[DATAREST-593](https://jira.spring.io/browse/DATAREST-593?redirect=false)** and commented

`@Valid` annotations are not respected on `@RepositoryRestController` annotated controllers as they are with `@Controller` and `@RestController` classes. This breaks with convention and expectation of developers.

---

**Affects:** 2.3 GA (Fowler)

**Issue Links:**
- [DATAREST-1266](https://jira.spring.io/browse/DATAREST-1266) `@BasePathAwareController` disables DTO validation
 (_**"is duplicated by"**_)

15 votes, 18 watchers

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by emaysyuk** [comment]
Doesn't work for @BasePathAwareController as well. Looks like Spring Data REST doesn't inject LocalValidatorFactoryBean instance into ExtendedServletRequestDataBinder while it resolves arguments and creates new binder.

**Comment by hmnshgpt455** [comment]
Faced the same issue
