### ISSUE TITLE
POST association url  fails for custom Jackson naming strategy [DATAREST-618]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-rest#992]
**[Michael Gugerell](https://jira.spring.io/secure/ViewProfile.jspa?name=tiresias)** opened **[DATAREST-618](https://jira.spring.io/browse/DATAREST-618?redirect=false)** and commented

1. Set naming strategy to pascal case. (See Datarest-556)
2. Post an entity with a relation:

```
{  "Foo":".../foos2" }
```

3. Exception "trying to instantiate Foo from String".

The problem does not occur using the default naming strategy

---

**Affects:** 2.3.1 (Fowler SR1)

**Comment by odrotbohm** [comment]
This ticket came up in the context of #2165, and we think the original problem should be solved with the fix for that. Please give the snapshots a try if you manage to find the time.
